### ISSUE TITLE
error tracking in crystal

### ISSUE THREAD

**Issue by sam0x17** [apex/up#775]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

It looks like there is no way to see the reason for a crash in crystal. I'm about to look for a third party solution for this, but is there anything in up that I'm missing? I'm able to tail the logs of my function, however I don't get the error output from crystal so have to use trial and error to figure out what is actually crashing.

example log output:
```
  Aug 11th 05:30:08pm ERRO staging adb5311 response: duration=213ms id=[REDACTED] ip=[REDACTED] method=GET path=/ size=656 B status=500
  Aug 11th 05:30:08pm INFO REPORT RequestId: db326011-7ce8-405e-811d-980ee385728b    Duration: 215.30 ms     Billed Duration: 300 ms         Memory Size: 512 MB  Max Memory Used: 105 MB
```

**Comment by sam0x17** [comment]
I figured it out -- the error was happening before initialization so it was lost by logging
